version: "3.4"

services:

  warehouse:
    image: ${REGISTRY}warehouse:${WAREHOUSE_VERSION:-latest}
    #    deploy:
# Commented due to low resources on local
#      resources:
#        reservations:
#          cpus: '2'
#        limits:
#          memory: 2G
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: prod
    labels:
      kompose.image-pull-policy: "IfNotPresent"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      start_period: 30s

  ######################## Mongo ##############################
  mongo:
    image: mongo:4.0-xenial
    expose:
      - 27017
    ports:
      - 27017:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all"]
    volumes:
      - mongo-data:/data/db
    labels:
      kompose.image-pull-policy: "Always"
      kompose.volume.size: 100Gi

volumes:
  mongo-data:
