name: CI Pipeline for PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build JAR
        run: |
          cd $GITHUB_WORKSPACE/nlp-processor
          ./gradlew clean build -PskipTests
          cd $GITHUB_WORKSPACE/nlp-processor
          ./gradlew clean build -PskipTests

  test:
    name: Run Test
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Patent Manager Test
        run: |
          cd $GITHUB_WORKSPACE/patent-manager
          ./gradlew unitTest
          ./gradlew intTest
      - name: NLP Processor Test
        run: |
          cd $GITHUB_WORKSPACE/nlp-processor
          ./gradlew unitTest
          ./gradlew intTest